language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git
  - sudo apt-get install -qq maven
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - cd javagit
  - mvn install
