package edu.nyu.cs.javagit.api.commands;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import edu.nyu.cs.javagit.utilities.CheckUtilities;

/**
 * Response data object for &lt;git-checkout&gt; command.
 */
public abstract class GitCheckoutResponse implements CommandResponse {

  /**
   * List of files that have been modified but not committed.
   */
  protected final List<String> modifiedFiles;
  /**
   * List of files added by &lt;git-add&gt; but not committed.
   */
  protected final List<String> addedFiles;
  /**
   * List of files deleted but not committed.
   */
  protected final List<String> deletedFiles;

  public GitCheckoutResponse() {
    modifiedFiles = new ArrayList<String>();
    addedFiles = new ArrayList<String>();
    deletedFiles = new ArrayList<String>();
  }

  /**
   * If git-checkout generates an error message, the error message is saved to String "error".
   */
  protected String error;

  /**
   * The new branch that is created and switched to by -b option provided by &lt;git-checkout&gt;.
   */
  protected String newBranch;

  /**
   * The name of the branch to which &lt;git-checkout&gt; switches.
   */
  protected String branch;

  /**
   * Returns the error string that was generated by &lt;git-checkout&gt; command
   * 
   * @return Error message
   */
  public String getError() {
    return error;
  }

  /**
   * Returns the newly created branch by -b option by &lt;git-checkout&gt;.
   * 
   * @return Name of the new branch
   */
  public String getNewBranch() {
    return newBranch;
  }

  /**
   * Returns the branch to which &lt;git-checkout&gt; switches to.
   * 
   * @return Name of the branch
   */
  public String getBranch() {
    return branch;
  }

  /**
   * Returns iterator to the modified files list
   * 
   * @return iterator to the list.
   */
  public Iterator<String> getModifiedFilesIterator() {
    return (new ArrayList<String>(modifiedFiles).iterator());
  }

  /**
   * Gets iterator to the copy of addedFiles list.
   * 
   * @return iterator to the list.
   * 
   */
  public Iterator<String> getAddedFilesIterator() {
    return (new ArrayList<String>(addedFiles).iterator());
  }

  /**
   * Gets iterator to the copy of deletedFiles list.
   * 
   * @return iterator to the list.
   */
  public Iterator<String> getDeletedFilesIterator() {
    return (new ArrayList<String>(deletedFiles).iterator());
  }

  /**
   * Returns the file at a given location in the addedFiles list
   * 
   * @param index
   *          in the list and should be positive and less than no. of files added.
   * @return added file at the index in addedFiles list.
   */
  public String getAddedFile(int index) {
    CheckUtilities.checkIntIndexInListRange(addedFiles, index);
    return addedFiles.get(index);
  }

  /**
   * Returns the file at a given location in the deletedFiles list
   * 
   * @param index
   *          in the list and should be positive and less than no. of files deleted.
   * @return deleted file at the index in deleteFiles list.
   */
  public String getDeletedFile(int index) {
    CheckUtilities.checkIntIndexInListRange(deletedFiles, index);
    return deletedFiles.get(index);
  }

  /**
   * Returns the file at a given location in the modifiedFiles list.
   * 
   * @param index
   *          in the list and it should be positive and less than total no. of files modified.
   * @return modified file at the index in modifiedFiles list.
   */
  public String getModifiedFile(int index) {
    CheckUtilities.checkIntIndexInListRange(modifiedFiles, index);
    return modifiedFiles.get(index);
  }

  /**
   * Gets the total no. of files in addedFiles list.
   * 
   * @return no. of files
   */
  public int getNoOfAddedFiles() {
    return addedFiles.size();
  }

  /**
   * Gets total no. of files in modifiedFiles list.
   * 
   * @return no. of files.
   */
  public int getNoOfModifiedFiles() {
    return modifiedFiles.size();
  }

  /**
   * Gets total no. o files in addedFiles List.
   * 
   * @return no. of files.
   */
  public int getNoOfDeletedFiles() {
    return deletedFiles.size();
  }
}
